import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
await mkdir('test-results', { recursive: true });
const browser = await chromium.launch({ executablePath: '/root/.cache/ms-playwright/chromium-1228/chrome-linux64/chrome', headless: true, args: ['--no-sandbox', '--enable-webgl', '--ignore-gpu-blocklist', '--use-gl=angle', '--use-angle=swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', msg => { if (msg.type() === 'error' || msg.type() === 'warning') console.log(msg.type(), msg.text().slice(0, 1000)); });
await page.goto('http://localhost:5173', { waitUntil: 'domcontentloaded' });
await page.waitForFunction(() => !!window.__BADAGUAN__, null, { timeout: 60000 });
await page.evaluate(() => { window.__BADAGUAN__.renderer.setPixelRatio(.65); });
await page.waitForTimeout(1500);
console.log(await page.evaluate(() => ({ ready: !!window.__BADAGUAN__, draw: window.__BADAGUAN__?.renderer.info.render, fonts: document.fonts.status, canvas: document.querySelector('canvas')?.getBoundingClientRect().toJSON() })));
await page.screenshot({ path: 'test-results/desktop.png', fullPage: true });
console.log('Page errors:', errors);
await page.evaluate(()=>window.__BADAGUAN__.renderer.setPixelRatio(.35));
console.log(await page.evaluate(()=>({overflow:document.querySelector('.sidebar').scrollHeight,sidebar:document.querySelector('.sidebar').clientHeight, elements:[...document.querySelector('.sidebar').children].map(e=>({class:e.className,top:e.offsetTop,height:e.offsetHeight,margin:getComputedStyle(e).marginTop}))})));
const position = () => page.evaluate(() => window.__BADAGUAN__.camera.position.toArray());
const stop = () => page.evaluate(() => window.__BADAGUAN__.setGuided(false));
await page.locator('[data-view="princess"]').click();
await page.waitForFunction(() => Math.abs(window.__BADAGUAN__.camera.position.z + 16) < .05, null, {timeout:45000});
assert.equal(await page.locator('#scene-location').textContent(), '公主楼');
await page.locator('[data-view="coast"]').click();
await page.waitForFunction(() => Math.abs(window.__BADAGUAN__.camera.position.z + 56) < .05, null, {timeout:45000});
console.log('PASS: landmark transitions');
await page.screenshot({path:'test-results/coast.png'});
await page.locator('#nav-wander').click();
await page.waitForFunction(() => Math.abs(window.__BADAGUAN__.camera.position.z - 38) < .05, null, {timeout:45000});
await page.locator('#start-button').click();
const initial=await position();
await page.keyboard.down('w'); await page.waitForFunction(z=>window.__BADAGUAN__.camera.position.z<z-.1,initial[2],{timeout:20000}); await page.keyboard.up('w');
assert.ok((await position())[2] < initial[2] - .1, 'W moves camera forward');
const beforeAltitude=await position();
await page.keyboard.down('e');await page.waitForFunction(y=>window.__BADAGUAN__.camera.position.y>y+.1,beforeAltitude[1],{timeout:20000});await page.keyboard.up('e');
assert.ok((await position())[1]>beforeAltitude[1], 'E raises the camera');
const yaw=await page.evaluate(()=>window.__BADAGUAN__.camera.rotation.y);
await page.mouse.move(800,420);await page.mouse.down();await page.mouse.move(910,450,{steps:5});await page.mouse.up();
assert.ok(Math.abs((await page.evaluate(()=>window.__BADAGUAN__.camera.rotation.y))-yaw)>.1,'Mouse drag rotates');
await page.locator('#guide-mode').click();await page.locator('#start-button').click();
assert.equal(await page.locator('#start-label').textContent(),'暂停导览');
await page.keyboard.press('Escape');const paused=await position();await page.waitForTimeout(500);
assert.deepEqual(await position(),paused,'Escape stops guide transition');
await page.locator('#start-button').click();await page.mouse.move(810,430);await page.mouse.wheel(0,120);
await page.waitForTimeout(300);
assert.equal(await page.locator('#start-label').textContent(),'出发，看遍八大关','Wheel cancels guide');
await stop();console.log('PASS: movement, elevation, view drag, guide cancellation');
await page.locator('[data-season="summer"]').click();
assert.equal(await page.locator('[data-season="summer"]').getAttribute('aria-pressed'),'true');
assert.equal(await page.locator('#weather-text').textContent(),'夏日晴时');
await page.locator('#time-slider').focus();await page.keyboard.press('End');
assert.ok((await page.locator('#time-number').textContent()).includes('19:00'));
await page.locator('#sound-switch').click();
await page.waitForFunction(()=>document.querySelector('#sound-switch').getAttribute('aria-checked')==='true');
await page.locator('#sound-switch').click();
await page.waitForFunction(()=>document.querySelector('#sound-switch').getAttribute('aria-checked')==='false');
await page.locator('#map-button').click();assert.equal(await page.locator('#map-card').evaluate(e=>e.inert),true);
await page.locator('#map-button').click();assert.equal(await page.locator('#map-card').evaluate(e=>e.inert),false);
console.log('PASS: seasons, time, sound, map');
await page.locator('#help-button').click();assert.equal(await page.locator('#guide-dialog').evaluate(e=>e.open),true);
const modalPosition=await position();await page.keyboard.press('w');assert.deepEqual(await position(),modalPosition,'Modal blocks keyboard travel');
await page.locator('#guide-close').click();
await page.locator('#nav-notes').click();assert.equal(await page.locator('#notes-dialog').evaluate(e=>e.open),true);
assert.ok((await page.locator('.source-note').textContent()).includes('艺术化重构'));
await page.locator('#notes-dialog .dialog-close').click();
const downloaded=page.waitForEvent('download');await page.locator('#photo-button').click();const download=await downloaded;
assert.ok(download.suggestedFilename().endsWith('.png'));await download.saveAs('test-results/postcard.png');
await page.locator('#fullscreen-button').click();await page.waitForTimeout(300);
assert.equal(await page.evaluate(()=>!!document.fullscreenElement),true);await page.locator('#fullscreen-button').click();
await page.locator('[data-season="autumn"]').click();await page.locator('#time-slider').evaluate(e=>{e.value='16.5';e.dispatchEvent(new Event('input',{bubbles:true}));});
await page.locator('#free-mode').click();await page.evaluate(()=>window.__BADAGUAN__.goTo('lane',true));
await page.setViewportSize({width:390,height:844});
await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(600);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Mobile has no horizontal overflow');
await page.screenshot({path:'test-results/mobile.png',fullPage:true});
const touchBefore=await position();const touchBox=await page.locator('[data-key="KeyW"]').boundingBox();
await page.mouse.move(touchBox.x+10,touchBox.y+10);await page.mouse.down();await page.waitForFunction(z=>window.__BADAGUAN__.camera.position.z<z-.1,touchBefore[2],{timeout:20000});await page.mouse.up();
assert.ok((await position())[2]<touchBefore[2],'Touch movement works');
assert.deepEqual(errors,[],'No page errors');
console.log('PASS: destinations, keyboard, drag, elevation, guide interruption, seasons, time, sound, map, dialogs, photo, fullscreen, responsive layout, touch movement.');
await browser.close();
